services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_ARGS=--save 30 1000
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis_data:/data
  app:
    build: .
    ports:
      - 7860:7860
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    #   - CUDA_VISIBLE_DEVICES=0
    # # Uncomment the following lines if you want to use GPU.
    # # Requires NVIDIA Container Toolkit to be installed on the host.
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
# volumes:
#   redis_data:
