# Model config
MODEL_NAME = "Derify/ChemMRL-alpha"
SUPPORTED_EMBEDDING_DIMENSIONS = [1024, 768, 512, 256, 128, 64, 32, 16, 8, 4, 2]
EMBEDDING_DIMENSION = max(SUPPORTED_EMBEDDING_DIMENSIONS)

# HNSW config
HNSW_K = 6
HNSW_DISTANCE_METRIC = "IP"  # embedding vectors are normalize so COSINE = IP
HNSW_INITIAL_CAP = 300
HNSW_M = 12
HNSW_EF_CONSTRUCTION = 150
HNSW_EF_RUNTIME = 10
